from flask import Flask, render_template, request, jsonify
import numpy as np
import json
import random
import time
import mysql.connector
import os

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Fraud Detection Logic
# ---------------------------------------------------------------------------
# REPLACE this stub with your real trained model:
#
#   import joblib
#   model = joblib.load("ml/fraud_model.pkl")
#   scaler = joblib.load("ml/scaler.pkl")
#
# Then replace `mock_predict()` with:
#   scaled = scaler.transform([[amount, v1, v2, v3, v4, v5]])
#   prob   = model.predict_proba(scaled)[0][1]
# ---------------------------------------------------------------------------

FRAUD_THRESHOLD = 0.50  
def mock_predict(amount: float, features: list[float]) -> dict:
    """
    Stub predictor. Produces a realistic-looking probability score
    from the raw feature values so the UI works end-to-end.
    Delete this once you load your real model.
    """
    # Heuristic: large amounts + extreme V-values push fraud probability up
    feature_signal = sum(abs(f) for f in features) / (len(features) or 1)
    raw = (amount / 5000) * 0.4 + (feature_signal / 10) * 0.6
    prob = min(max(raw + random.gauss(0, 0.05), 0.0), 1.0)
    return {
        "fraud_probability": round(prob, 4),
        "is_fraud": prob >= FRAUD_THRESHOLD,
        "risk_score": int(prob * 100),
    }

# ---------------------------------------------------------------------------
# Page Routes
# ---------------------------------------------------------------------------

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/dashboard")
def dashboard():
    return render_template("dashboard.html")


@app.route("/analytics")
def analytics():
    return render_template("analytics.html")


@app.route("/about")
def about():
    return render_template("about.html")


# ---------------------------------------------------------------------------
# API — Prediction Endpoint
# ---------------------------------------------------------------------------
@app.route("/api/predict", methods=["POST"])
def predict():
    """
    Accepts JSON: { amount, v1..v5, merchant, card_type }
    Returns JSON with prediction results + echoed transaction data.
    """
    try:
        data = request.get_json(force=True)

        amount    = float(data.get("amount", 0))
        features  = [float(data.get(f"v{i}", 0)) for i in range(1, 6)]
        merchant  = data.get("merchant", "Unknown Merchant")
        card_type = data.get("card_type", "Visa")

        # ── Simulate model latency (remove in production) ──
        time.sleep(0.8)

        # 1. Get the mock prediction result
        result = mock_predict(amount, features)
        is_fraud = result.get("is_fraud", False)
        risk_score = result.get("risk_score", 15) # Default mock risk if missing

        # 2. CONNECT TO DATABASE AND SAVE
        import mysql.connector
        db = mysql.connector.connect(
            host=os.environ.get("MYSQLHOST", "localhost"),
            user=os.environ.get("MYSQLUSER", "root"),
            password=os.environ.get("MYSQLPASSWORD", "passion"),
            database=os.environ.get("MYSQLDATABASE", "fraud_detection_db"),
            port=os.environ.get("MYSQLPORT", 3306)
        )
        cursor = db.cursor()

        # Notice we are explicitly saving the Merchant and Risk_Score here!
        sql = """
            INSERT INTO transactions 
            (Amount, V1, V2, V3, V4, V5, Class, Merchant, Risk_Score) 
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """
        values = (
            amount, 
            features[0], features[1], features[2], features[3], features[4], 
            int(is_fraud), 
            merchant, 
            risk_score
        )
        
        cursor.execute(sql, values)
        db.commit()

        # Get the real ID generated by the database
        real_txn_id = cursor.lastrowid

        cursor.close()
        db.close()

        # 3. Build enriched response with the REAL database ID
        response = {
            "success": True,
            "transaction": {
                "id":          real_txn_id, 
                "amount":      round(amount, 2),
                "merchant":    merchant,
                "card_type":   card_type,
                "timestamp":   time.strftime("%Y-%m-%d %H:%M:%S"),
                "features":    {f"V{i+1}": features[i] for i in range(len(features))},
            },
            "prediction": result,
        }

        return jsonify(response), 200

    except Exception as exc:
        print(f"PREDICT ERROR: {str(exc)}")
        return jsonify({"success": False, "error": str(exc)}), 400

# ---------------------------------------------------------------------------
# API — Analytics Stats (mock data; swap for real DB queries)
# ---------------------------------------------------------------------------
@app.route("/api/stats")
def stats():
    return jsonify({
        "total_transactions": 284_807,
        "fraud_cases":        492,
        "fraud_rate":         0.00173,
        "model_accuracy":     0.9994,
        "precision":          0.937,
        "recall":             0.872,
        "f1_score":           0.903,
        "auc_roc":            0.9825,
    })

@app.route("/api/history", methods=["GET"])
def get_history():
    try:
        # 1. Connect to database
        fresh_connection = mysql.connector.connect(
            host=os.environ.get("MYSQLHOST", "localhost"),
            user=os.environ.get("MYSQLUSER", "root"),
            password=os.environ.get("MYSQLPASSWORD", "passion"),
            database=os.environ.get("MYSQLDATABASE", "fraud_detection_db"),
            port=os.environ.get("MYSQLPORT", 3306)
        )
        
        # 2. Fetch data
        cursor = fresh_connection.cursor(dictionary=True)
        cursor.execute("SELECT * FROM transactions ORDER BY id DESC LIMIT 15")
        rows = cursor.fetchall()
        
        # 3. Close connections
        cursor.close()
        fresh_connection.close()
        
        # 4. Format the history
        history = []
        for row in rows:
            history.append({
                "transaction": {
                    "id": row["id"],
                    "amount": row["Amount"],
                    "merchant": row.get("Merchant", "Unknown Merchant"), 
                },
                "prediction": {
                    "is_fraud": bool(row["Class"]),
                    "risk_score": row.get("Risk_Score", 88 if row["Class"] == 1 else 12) 
                }
            })
            
        # THIS is the crucial return statement that Flask was missing!
        return jsonify({"success": True, "history": history})
        
    except Exception as e:
        # If it crashes, it MUST also return the error to the browser
        print(f"API ERROR: {str(e)}") 
        return jsonify({"success": False, "error": str(e)})

@app.route("/env-test")
def env_test():
    return {
        "MYSQLHOST": os.environ.get("MYSQLHOST"),
        "MYSQLUSER": os.environ.get("MYSQLUSER"),
        "MYSQLDATABASE": os.environ.get("MYSQLDATABASE"),
        "MYSQLPORT": os.environ.get("MYSQLPORT")
    }

@app.route("/db-check")
def db_check():
    return {
        "host": os.getenv("MYSQLHOST"),
        "database": os.getenv("MYSQLDATABASE"),
        "user": os.getenv("MYSQLUSER"),
        "password_exists": os.getenv("MYSQLPASSWORD") is not None,
        "port": os.getenv("MYSQLPORT")
    }

@app.route("/mysql-url")
def mysql_url():
    return {
        "mysql_url_exists": os.getenv("MYSQL_URL") is not None
    }
@app.route("/db-test")
def db_test():
    try:
        conn = mysql.connector.connect(
            host=os.getenv("MYSQLHOST"),
            user=os.getenv("MYSQLUSER"),
            password=os.getenv("MYSQLPASSWORD"),
            database=os.getenv("MYSQLDATABASE"),
            port=int(os.getenv("MYSQLPORT", 3306))
        )

        cur = conn.cursor()
        cur.execute("SELECT 1")
        result = cur.fetchone()

        cur.close()
        conn.close()

        return {"success": True, "result": result[0]}

    except Exception as e:
        return {"success": False, "error": str(e)}

@app.route("/connection-info")
def connection_info():
    return {
        "host": os.getenv("MYSQLHOST"),
        "user": os.getenv("MYSQLUSER"),
        "database": os.getenv("MYSQLDATABASE"),
        "port": os.getenv("MYSQLPORT"),
        "mysql_url_exists": os.getenv("MYSQL_URL") is not None
    }

from urllib.parse import urlparse

@app.route("/mysql-url-test")
def mysql_url_test():
    try:
        mysql_url = os.getenv("MYSQL_URL")

        if not mysql_url:
            return {"success": False, "error": "MYSQL_URL not found"}

        parsed = urlparse(mysql_url)

        conn = mysql.connector.connect(
            host=parsed.hostname,
            user=parsed.username,
            password=parsed.password,
            database=parsed.path.lstrip("/"),
            port=parsed.port
        )

        cur = conn.cursor()
        cur.execute("SELECT CURRENT_USER();")
        result = cur.fetchone()

        cur.close()
        conn.close()

        return {
            "success": True,
            "current_user": str(result[0])
        }

    except Exception as e:
        return {
            "success": False,
            "error": str(e)
        }

@app.route("/fix-schema")
def fix_schema():
    try:
        conn = mysql.connector.connect(
            host=os.getenv("MYSQLHOST"),
            user=os.getenv("MYSQLUSER"),
            password=os.getenv("MYSQLPASSWORD"),
            database=os.getenv("MYSQLDATABASE"),
            port=int(os.getenv("MYSQLPORT", 3306))
        )

        cur = conn.cursor()

        try:
            cur.execute("""
                ALTER TABLE transactions
                ADD COLUMN Merchant VARCHAR(255)
            """)
        except:
            pass

        try:
            cur.execute("""
                ALTER TABLE transactions
                ADD COLUMN Risk_Score INT
            """)
        except:
            pass

        conn.commit()

        cur.close()
        conn.close()

        return {
            "success": True,
            "message": "Schema updated"
        }

    except Exception as e:
        return {
            "success": False,
            "error": str(e)
        }

if __name__ == "__main__":
    app.run(
        host="0.0.0.0",
        port=int(os.environ.get("PORT", 5000))
    )
